name: flutter_structure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.1
  go_router: ^14.2.7
  gap: ^3.0.1
  meta: ^1.15.0
  http: ^1.2.2
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
